sudo apt update && sudo apt upgrade -y
sudo apt install gpsd gpsd-clients python3-pip sqlite3 -y
pip3 install pynmea2 scikit-learn pandas numpy matplotlib

 4. Configure gpsd for the USB GPS Module
A. Identify the GPS USB device:
bash
Copy
Edit
ls /dev/ttyUSB*
Usually /dev/ttyUSB0.

B. Edit /etc/default/gpsd:
bash
Copy
Edit
sudo nano /etc/default/gpsd
Change or set the following:

ini
Copy
Edit
START_DAEMON="true"
GPSD_OPTIONS=""
DEVICES="/dev/ttyUSB0"
USBAUTO="true"
GPSD_SOCKET="/var/run/gpsd.sock"
C. Restart gpsd:
bash
Copy
Edit
sudo systemctl restart gpsd
sudo systemctl enable gpsd
D. Test with cgps:
bash
Copy
Edit
cgps -s
You should see live GPS data.

chmod +x ~/gps_anomaly/scripts/start_logging.sh

sudo apt update
sudo apt install python3-venv -y
python3 -m venv ~/gps_anomaly/venv
source ~/gps_anomaly/venv/bin/activate
pip install pynmea2 pandas matplotlib scikit-learn



[Unit]
Description=GPS Data Processing Service
After=network.target

[Service]
ExecStart=/home/pi/gps_anomaly/venv/bin/python3 /home/pi/gps_anomaly/main_process.py
WorkingDirectory=/home/pi/gps_anomaly
User=pi
Group=pi
Restart=always

[Install]
WantedBy=multi-user.target

Save it as /etc/systemd/system/gps_processing.service.

Run:

bash
Copy
Edit
sudo systemctl daemon-reload
sudo systemctl enable gps_processing.service
sudo systemctl start gps_processing.service